version: "3"
services:
  web-app:    
    build:
      context: ./
      dockerfile: Dockerfile    
    container_name: web-app
    ports:
      - "8080:8080"    
    environment:
      - TZ=America/Tijuana
      - XAL_DIGITAL_API_BASE_URL=http://localhost
      - SERVER_PORT=8080
