---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ (splitList "/" .Values.deployment.fsaWebApp.imageName) | last }}
  namespace: {{ .Values.namespace }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}  
spec:
  ingressClassName: {{ .Values.ingress.className }} 
  tls:
    - hosts:
        - {{ .Values.ingress.host }}       
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: {{ .Values.ingress.path }}
          pathType: {{ .Values.ingress.pathType }}
          backend:
            service:
              name: {{ .Values.deployment.fsaWebApp.service.name }}
              port:
                number: {{ .Values.deployment.fsaWebApp.service.port }}